namespace Nop.Services.Installation;

/// <summary>
/// The "ConditionsOfUse" topic copy, Arabic-first with English as its localized value.
/// Shared by the installer and the migration that replaces the old placeholder, so the
/// terms live in one place.
///
/// Plain h2/p/ul markup only: .topic-page .page-body in brand.css styles it (both
/// directions, every width), and an admin can keep editing it in the rich editor.
/// </summary>
public static class ConditionsOfUseTopic
{
    public const string ArabicTitle = "شروط الاستخدام";

    public const string EnglishTitle = "Terms and Conditions";

    /// <summary>The body the installer used to seed; the migration only replaces this</summary>
    public const string ArabicPlaceholder = "<p>اكتب هنا شروط الاستخدام. يمكنك تعديل هذا النص من لوحة التحكم.</p>";

    public const string ArabicBody =
        "<p>مرحباً بك في متجر شركة العربية الدولية للأجهزة الإلكتروني. تنظّم هذه الشروط استخدامك للموقع وشراءك منه، ويُعدّ دخولك إلى الموقع أو إتمامك لأي طلب موافقةً منك عليها، فنرجو قراءتها بعناية.</p>"
        + "<h2>التعريفات</h2><ul>"
        + "<li><strong>الشركة أو «نحن»:</strong> شركة العربية الدولية للأجهزة، ومقرها الرياض، المملكة العربية السعودية.</li>"
        + "<li><strong>الموقع:</strong> المتجر الإلكتروني للشركة وجميع صفحاته وخدماته.</li>"
        + "<li><strong>العميل أو «أنت»:</strong> كل من يتصفح الموقع أو ينشئ حساباً فيه أو يشتري من خلاله.</li>"
        + "<li><strong>المنتجات:</strong> الأجهزة الكهربائية المنزلية وقطع الغيار وخدمات الصيانة المعروضة على الموقع.</li>"
        + "</ul>"
        + "<h2>الحساب والتسجيل</h2><ul>"
        + "<li>يجب أن يكون عمرك 18 عاماً فأكثر لإنشاء حساب أو إتمام عملية شراء.</li>"
        + "<li>تلتزم بتقديم بيانات صحيحة ومحدّثة، بما فيها الاسم ورقم الجوال وعنوان التوصيل.</li>"
        + "<li>أنت مسؤول عن سرية كلمة المرور وعن كل ما يتم من خلال حسابك، وعليك إبلاغنا فوراً عند الاشتباه بأي استخدام غير مصرّح به.</li>"
        + "<li>يحق للشركة تعليق أي حساب أو إلغاؤه عند مخالفة هذه الشروط أو الاشتباه بإساءة الاستخدام.</li>"
        + "</ul>"
        + "<h2>المنتجات والأسعار</h2><ul>"
        + "<li>نحرص على عرض أوصاف المنتجات وصورها ومواصفاتها بدقة، وقد تختلف الألوان أو التفاصيل اختلافاً طفيفاً عن الصور بحسب إعدادات شاشتك.</li>"
        + "<li>الأسعار معروضة بالريال السعودي وشاملة لضريبة القيمة المضافة ما لم يُذكر خلاف ذلك.</li>"
        + "<li>الأسعار والعروض والتوفّر قابلة للتغيير دون إشعار مسبق، ويُعتمد السعر الظاهر لحظة تأكيد الطلب.</li>"
        + "<li>إذا ظهر سعر خاطئ نتيجة خطأ تقني أو مطبعي، يحق لنا إلغاء الطلب وإعادة كامل المبلغ المدفوع إليك.</li>"
        + "</ul>"
        + "<h2>الطلبات والدفع</h2><ul>"
        + "<li>يُعدّ الطلب مقبولاً بعد وصول رسالة تأكيد منا، ويحق لنا رفض أي طلب أو إلغاؤه عند نفاد الكمية أو تعذّر التحقق من بيانات الدفع أو العنوان.</li>"
        + "<li>يتم الدفع بوسائل الدفع المتاحة عند إتمام الطلب، وتُعالَج المدفوعات الإلكترونية عبر مزوّدي دفع معتمدين، ولا نحتفظ ببيانات بطاقتك.</li>"
        + "<li>تصدر فاتورة ضريبية إلكترونية لكل طلب، ويُرجى الاحتفاظ بها لأنها شرط للاستفادة من الضمان.</li>"
        + "</ul>"
        + "<h2>التوصيل والتركيب</h2><ul>"
        + "<li>نوصل الطلبات داخل المملكة العربية السعودية إلى العنوان المحدد في الطلب، وتظهر مدة التوصيل ورسومه قبل تأكيد الطلب.</li>"
        + "<li>مواعيد التوصيل تقديرية، وقد تتأخر لأسباب خارجة عن إرادتنا، وسنبلغك بأي تأخير.</li>"
        + "<li>عند الاستلام، يُرجى فحص المنتج وتغليفه وإبلاغ مندوب التوصيل أو خدمة العملاء فوراً بأي تلف ظاهر.</li>"
        + "<li>تُقدَّم خدمة التركيب للأجهزة التي تتطلبها وفق ما هو موضح في صفحة المنتج.</li>"
        + "</ul>"
        + "<h2>الإرجاع والاستبدال</h2><ul>"
        + "<li>يحق لك إرجاع المنتج أو استبداله خلال سبعة (7) أيام من تاريخ الاستلام، وفقاً لنظام التجارة الإلكترونية في المملكة.</li>"
        + "<li>يُشترط أن يكون المنتج بحالته الأصلية، غير مستخدم أو مركّب، ومع تغليفه وملحقاته وفاتورة الشراء.</li>"
        + "<li>إذا كان المنتج معيباً أو مخالفاً للطلب، نتحمل تكاليف إعادته ونستبدله أو نعيد المبلغ كاملاً.</li>"
        + "<li>يُعاد المبلغ بطريقة الدفع الأصلية بعد فحص المنتج المرتجع والتحقق من استيفاء الشروط.</li>"
        + "</ul>"
        + "<h2>الضمان والصيانة</h2>"
        + "<p>تتمتع منتجاتنا بضمان شامل لمدة سنتين يشمل الصيانة المجانية خلال فترة الضمان عند تقديم فاتورة الشراء الأصلية. تخضع تفاصيل الضمان وخدمات الصيانة لسياسة الصيانة المنشورة على الموقع، ولا يشمل الضمان الأعطال الناتجة عن سوء الاستخدام أو التركيب من غير فنيينا أو تذبذب التيار الكهربائي.</p>"
        + "<h2>الاستخدام المقبول</h2>"
        + "<p>تلتزم باستخدام الموقع لأغراض مشروعة فقط، ويُحظر عليك:</p><ul>"
        + "<li>انتحال شخصية الغير أو تقديم بيانات مضللة.</li>"
        + "<li>محاولة الوصول غير المصرّح به إلى الموقع أو أنظمته أو حسابات العملاء الآخرين.</li>"
        + "<li>نشر أي محتوى مسيء أو مخالف للأنظمة أو الآداب العامة في التقييمات أو المراسلات.</li>"
        + "<li>استخدام أدوات آلية لجمع البيانات من الموقع أو التأثير على أدائه.</li>"
        + "</ul>"
        + "<h2>الملكية الفكرية</h2>"
        + "<p>جميع محتويات الموقع من نصوص وصور وشعارات وتصاميم وعلامات تجارية مملوكة للشركة أو لأصحابها المرخِّصين، ولا يجوز نسخها أو إعادة نشرها أو استخدامها تجارياً دون موافقة كتابية مسبقة.</p>"
        + "<h2>حدود المسؤولية</h2>"
        + "<p>نسعى لإبقاء الموقع متاحاً ودقيقاً، لكننا لا نضمن خلوّه من الانقطاع أو الأخطاء. وفي حدود ما تسمح به الأنظمة، لا تتجاوز مسؤولية الشركة تجاه أي طلب قيمة المنتج المشترى، ولا تتحمل الشركة الأضرار غير المباشرة الناتجة عن استخدام الموقع أو تعذّر استخدامه.</p>"
        + "<h2>الخصوصية وحماية البيانات</h2>"
        + "<p>نجمع بياناتك الشخصية ونعالجها لتنفيذ طلباتك وتقديم خدماتنا فقط، وفقاً لنظام حماية البيانات الشخصية في المملكة العربية السعودية ولسياسة الخصوصية المنشورة على الموقع.</p>"
        + "<h2>تعديل الشروط</h2>"
        + "<p>يحق للشركة تعديل هذه الشروط في أي وقت، وتسري التعديلات من تاريخ نشرها على هذه الصفحة. ويُعدّ استمرارك في استخدام الموقع بعد النشر موافقةً على الشروط المعدّلة، ولا تسري التعديلات على الطلبات المؤكدة قبل نشرها.</p>"
        + "<h2>النظام الواجب التطبيق</h2>"
        + "<p>تخضع هذه الشروط وتُفسَّر وفقاً للأنظمة المعمول بها في المملكة العربية السعودية، وتختص المحاكم المختصة في مدينة الرياض بالنظر في أي نزاع ينشأ عنها، مع حرصنا على حل أي خلاف ودياً أولاً.</p>"
        + "<h2>تواصل معنا</h2>"
        + "<p>لأي استفسار حول هذه الشروط، يسعدنا تواصلك معنا عبر الرقم الموحد المجاني <strong>8001244080</strong> أو من خلال <a href=\"/contactus\">صفحة اتصل بنا</a>.</p>";

    public const string EnglishBody =
        "<p>Welcome to the online store of Arabian Appliances Company. These terms govern your use of the website and your purchases through it. By browsing the site or placing an order you agree to them, so please read them carefully.</p>"
        + "<h2>Definitions</h2><ul>"
        + "<li><strong>The Company, \"we\" or \"us\":</strong> Arabian Appliances Company, headquartered in Riyadh, Kingdom of Saudi Arabia.</li>"
        + "<li><strong>The Website:</strong> the Company's online store and all of its pages and services.</li>"
        + "<li><strong>The Customer or \"you\":</strong> anyone who browses the website, creates an account on it or buys through it.</li>"
        + "<li><strong>Products:</strong> the home appliances, spare parts and maintenance services offered on the website.</li>"
        + "</ul>"
        + "<h2>Account and Registration</h2><ul>"
        + "<li>You must be 18 years of age or older to create an account or complete a purchase.</li>"
        + "<li>You agree to provide accurate, up-to-date information, including your name, mobile number and delivery address.</li>"
        + "<li>You are responsible for keeping your password confidential and for all activity under your account, and must notify us immediately of any suspected unauthorised use.</li>"
        + "<li>The Company may suspend or close any account that breaches these terms or is suspected of misuse.</li>"
        + "</ul>"
        + "<h2>Products and Prices</h2><ul>"
        + "<li>We take care to describe and picture our products accurately; colours and details may differ slightly from the images depending on your screen.</li>"
        + "<li>Prices are shown in Saudi Riyals and include VAT unless stated otherwise.</li>"
        + "<li>Prices, offers and availability may change without prior notice. The price shown when you confirm your order is the one that applies.</li>"
        + "<li>If a price is displayed in error due to a technical or typographical mistake, we may cancel the order and refund the full amount paid.</li>"
        + "</ul>"
        + "<h2>Orders and Payment</h2><ul>"
        + "<li>An order is accepted once you receive our confirmation. We may decline or cancel an order if stock runs out or the payment or address details cannot be verified.</li>"
        + "<li>Payment is made using the methods available at checkout. Card payments are processed by licensed payment providers, and we do not store your card details.</li>"
        + "<li>An electronic tax invoice is issued for every order. Please keep it, as it is required to claim the warranty.</li>"
        + "</ul>"
        + "<h2>Delivery and Installation</h2><ul>"
        + "<li>We deliver within the Kingdom of Saudi Arabia to the address given in the order. Delivery time and charges are shown before you confirm.</li>"
        + "<li>Delivery dates are estimates and may be affected by circumstances beyond our control; we will let you know of any delay.</li>"
        + "<li>On delivery, please inspect the product and its packaging and report any visible damage to the courier or customer service straight away.</li>"
        + "<li>Installation is provided for appliances that require it, as described on the product page.</li>"
        + "</ul>"
        + "<h2>Returns and Exchanges</h2><ul>"
        + "<li>You may return or exchange a product within seven (7) days of receiving it, in line with the Saudi E-Commerce Law.</li>"
        + "<li>The product must be in its original condition, unused and uninstalled, with its packaging, accessories and purchase invoice.</li>"
        + "<li>If a product is defective or not as ordered, we cover the return costs and replace it or refund the full amount.</li>"
        + "<li>Refunds are made to the original payment method once the returned product has been inspected and the conditions confirmed.</li>"
        + "</ul>"
        + "<h2>Warranty and Maintenance</h2>"
        + "<p>Our products carry a comprehensive two-year warranty, including free maintenance during the warranty period on presentation of the original purchase invoice. Warranty and service details are set out in the Maintenance Policy published on the website. The warranty does not cover faults caused by misuse, installation by anyone other than our technicians, or power fluctuations.</p>"
        + "<h2>Acceptable Use</h2>"
        + "<p>You agree to use the website for lawful purposes only. You must not:</p><ul>"
        + "<li>Impersonate another person or provide misleading information.</li>"
        + "<li>Attempt unauthorised access to the website, its systems or other customers' accounts.</li>"
        + "<li>Post offensive or unlawful content in reviews or correspondence.</li>"
        + "<li>Use automated tools to harvest data from the website or interfere with its operation.</li>"
        + "</ul>"
        + "<h2>Intellectual Property</h2>"
        + "<p>All website content, including text, images, logos, designs and trademarks, is owned by the Company or its licensors and may not be copied, republished or used commercially without prior written consent.</p>"
        + "<h2>Limitation of Liability</h2>"
        + "<p>We strive to keep the website available and accurate but do not guarantee it will be uninterrupted or error-free. To the extent permitted by law, the Company's liability for any order does not exceed the value of the product purchased, and the Company is not liable for indirect damages arising from the use of, or inability to use, the website.</p>"
        + "<h2>Privacy and Data Protection</h2>"
        + "<p>We collect and process your personal data solely to fulfil your orders and provide our services, in accordance with the Saudi Personal Data Protection Law and the Privacy Policy published on the website.</p>"
        + "<h2>Changes to These Terms</h2>"
        + "<p>The Company may amend these terms at any time. Changes take effect when published on this page, and continuing to use the website afterwards means you accept them. Changes do not apply to orders confirmed before they were published.</p>"
        + "<h2>Governing Law</h2>"
        + "<p>These terms are governed by and interpreted under the laws of the Kingdom of Saudi Arabia. The competent courts in Riyadh have jurisdiction over any dispute arising from them, though we will always try to resolve a disagreement amicably first.</p>"
        + "<h2>Contact Us</h2>"
        + "<p>For any questions about these terms, call our toll-free unified number <strong>8001244080</strong> or reach us through the <a href=\"/contactus\">Contact Us page</a>.</p>";
}