using FluentMigrator;
using Nop.Core.Infrastructure;
using Nop.Data;
using Nop.Data.Migrations;
using Nop.Services.Localization;

namespace Nop.Web.Framework.Migrations.UpgradeTo500;

/// <summary>
/// Arabic names for the activity log type dropdown. ActivityLogType.Name is plain DB text,
/// so the admin looks these up by system keyword and falls back to Name (English needs no rows).
/// </summary>
[NopUpdateMigration("2026-09-22 13:00:00", "5.00", UpdateMigrationType.Localization)]
public class ActivityLogTypeLocalizationMigration : MigrationBase
{
    /// <summary>Collect the UP migration expressions</summary>
    public override void Up()
    {
        if (!DataSettingsManager.IsDatabaseInstalled())
            return;

        //do not use DI, because it produces exception on the installation process
        var localizationService = EngineContext.Current.Resolve<ILocalizationService>();
        var languageService = EngineContext.Current.Resolve<ILanguageService>();

        var arabic = languageService.GetAllLanguages(showHidden: true)
            .FirstOrDefault(language => language.LanguageCulture.StartsWith("ar", StringComparison.OrdinalIgnoreCase));
        if (arabic is not null)
            localizationService.AddOrUpdateLocaleResource(new Dictionary<string, string>
            {
                ["Admin.ActivityLogType.AddNewAddressAttribute"] = "إضافة سمة عنوان جديدة",
                ["Admin.ActivityLogType.AddNewAddressAttributeValue"] = "إضافة قيمة سمة عنوان جديدة",
                ["Admin.ActivityLogType.AddNewAffiliate"] = "إضافة مسوق جديد",
                ["Admin.ActivityLogType.AddNewBlogPost"] = "إضافة تدوينة جديدة",
                ["Admin.ActivityLogType.AddNewCampaign"] = "إضافة حملة جديدة",
                ["Admin.ActivityLogType.AddNewCategory"] = "إضافة قسم جديد",
                ["Admin.ActivityLogType.AddNewCheckoutAttribute"] = "إضافة سمة دفع جديدة",
                ["Admin.ActivityLogType.AddNewCountry"] = "إضافة دولة جديدة",
                ["Admin.ActivityLogType.AddNewCurrency"] = "إضافة عملة جديدة",
                ["Admin.ActivityLogType.AddNewCustomerAttributeValue"] = "إضافة قيمة سمة عميل جديدة",
                ["Admin.ActivityLogType.AddNewCustomerAttribute"] = "إضافة سمة عميل جديدة",
                ["Admin.ActivityLogType.AddNewCustomerRole"] = "إضافة دور عميل جديد",
                ["Admin.ActivityLogType.AddNewCustomer"] = "إضافة عميل جديد",
                ["Admin.ActivityLogType.AddNewDiscount"] = "إضافة خصم جديد",
                ["Admin.ActivityLogType.AddNewEmailAccount"] = "إضافة حساب بريد إلكتروني جديد",
                ["Admin.ActivityLogType.AddNewFilterLevelValue"] = "إضافة قيمة مستوى تصفية جديدة",
                ["Admin.ActivityLogType.AddNewLanguage"] = "إضافة لغة جديدة",
                ["Admin.ActivityLogType.AddNewManufacturer"] = "إضافة شركة جديدة",
                ["Admin.ActivityLogType.AddNewMeasureDimension"] = "إضافة وحدة قياس أبعاد جديدة",
                ["Admin.ActivityLogType.AddNewMeasureWeight"] = "إضافة وحدة قياس وزن جديدة",
                ["Admin.ActivityLogType.AddNewMenuItem"] = "إضافة عنصر قائمة جديد",
                ["Admin.ActivityLogType.AddNewMenu"] = "إضافة قائمة جديدة",
                ["Admin.ActivityLogType.AddNewNews"] = "إضافة خبر جديد",
                ["Admin.ActivityLogType.AddNewProductAttribute"] = "إضافة سمة منتج جديدة",
                ["Admin.ActivityLogType.AddNewProduct"] = "إضافة منتج جديد",
                ["Admin.ActivityLogType.AddNewReviewType"] = "إضافة نوع مراجعة جديد",
                ["Admin.ActivityLogType.AddNewSetting"] = "إضافة إعداد جديد",
                ["Admin.ActivityLogType.AddNewSpecAttributeGroup"] = "إضافة مجموعة سمات مواصفات جديدة",
                ["Admin.ActivityLogType.AddNewSpecAttribute"] = "إضافة سمة مواصفات جديدة",
                ["Admin.ActivityLogType.AddNewStateProvince"] = "إضافة ولاية أو محافظة جديدة",
                ["Admin.ActivityLogType.AddNewStore"] = "إضافة متجر جديد",
                ["Admin.ActivityLogType.AddNewTopic"] = "إضافة موضوع جديد",
                ["Admin.ActivityLogType.AddNewVendorAttributeValue"] = "إضافة قيمة سمة بائع جديدة",
                ["Admin.ActivityLogType.AddNewVendorAttribute"] = "إضافة سمة بائع جديدة",
                ["Admin.ActivityLogType.AddNewVendor"] = "إضافة بائع جديد",
                ["Admin.ActivityLogType.AddNewWarehouse"] = "إضافة مستودع جديد",
                ["Admin.ActivityLogType.AddNewWidget"] = "إضافة عنصر واجهة جديد",
                ["Admin.ActivityLogType.AddSubscriptionType"] = "إضافة نوع اشتراك جديد",
                ["Admin.ActivityLogType.DeleteActivityLog"] = "حذف سجل النشاط",
                ["Admin.ActivityLogType.DeleteAddressAttributeValue"] = "حذف قيمة سمة عنوان",
                ["Admin.ActivityLogType.DeleteAddressAttribute"] = "حذف سمة عنوان",
                ["Admin.ActivityLogType.DeleteAffiliate"] = "حذف مسوق",
                ["Admin.ActivityLogType.DeleteBlogPostComment"] = "حذف تعليق على تدوينة",
                ["Admin.ActivityLogType.DeleteBlogPost"] = "حذف تدوينة",
                ["Admin.ActivityLogType.DeleteCampaign"] = "حذف حملة",
                ["Admin.ActivityLogType.DeleteCategory"] = "حذف قسم",
                ["Admin.ActivityLogType.DeleteCheckoutAttribute"] = "حذف سمة دفع",
                ["Admin.ActivityLogType.DeleteCountry"] = "حذف دولة",
                ["Admin.ActivityLogType.DeleteCurrency"] = "حذف عملة",
                ["Admin.ActivityLogType.DeleteCustomerAttributeValue"] = "حذف قيمة سمة عميل",
                ["Admin.ActivityLogType.DeleteCustomerAttribute"] = "حذف سمة عميل",
                ["Admin.ActivityLogType.DeleteCustomerRole"] = "حذف دور عميل",
                ["Admin.ActivityLogType.DeleteCustomer"] = "حذف عميل",
                ["Admin.ActivityLogType.DeleteDiscount"] = "حذف خصم",
                ["Admin.ActivityLogType.DeleteEmailAccount"] = "حذف حساب بريد إلكتروني",
                ["Admin.ActivityLogType.DeleteFilterLevelValue"] = "حذف قيمة مستوى تصفية",
                ["Admin.ActivityLogType.DeleteLanguage"] = "حذف لغة",
                ["Admin.ActivityLogType.DeleteManufacturer"] = "حذف شركة",
                ["Admin.ActivityLogType.DeleteMeasureDimension"] = "حذف وحدة قياس أبعاد",
                ["Admin.ActivityLogType.DeleteMeasureWeight"] = "حذف وحدة قياس وزن",
                ["Admin.ActivityLogType.DeleteMenuItem"] = "حذف عنصر قائمة",
                ["Admin.ActivityLogType.DeleteMenu"] = "حذف قائمة",
                ["Admin.ActivityLogType.DeleteMessageTemplate"] = "حذف قالب رسالة",
                ["Admin.ActivityLogType.DeleteNewsComment"] = "حذف تعليق على خبر",
                ["Admin.ActivityLogType.DeleteNews"] = "حذف خبر",
                ["Admin.ActivityLogType.DeleteOrder"] = "حذف طلب",
                ["Admin.ActivityLogType.DeletePlugin"] = "حذف إضافة برمجية",
                ["Admin.ActivityLogType.DeleteProductAttribute"] = "حذف سمة منتج",
                ["Admin.ActivityLogType.DeleteProductReview"] = "حذف مراجعة منتج",
                ["Admin.ActivityLogType.DeleteProduct"] = "حذف منتج",
                ["Admin.ActivityLogType.DeleteReturnRequest"] = "حذف طلب إرجاع",
                ["Admin.ActivityLogType.DeleteReviewType"] = "حذف نوع مراجعة",
                ["Admin.ActivityLogType.DeleteSetting"] = "حذف إعداد",
                ["Admin.ActivityLogType.DeleteSpecAttributeGroup"] = "حذف مجموعة سمات مواصفات",
                ["Admin.ActivityLogType.DeleteSpecAttribute"] = "حذف سمة مواصفات",
                ["Admin.ActivityLogType.DeleteStateProvince"] = "حذف ولاية أو محافظة",
                ["Admin.ActivityLogType.DeleteStore"] = "حذف متجر",
                ["Admin.ActivityLogType.DeleteSubscriptionType"] = "حذف نوع اشتراك",
                ["Admin.ActivityLogType.DeleteSystemLog"] = "حذف سجل النظام",
                ["Admin.ActivityLogType.DeleteTopic"] = "حذف موضوع",
                ["Admin.ActivityLogType.DeleteVendorAttributeValue"] = "حذف قيمة سمة بائع",
                ["Admin.ActivityLogType.DeleteVendorAttribute"] = "حذف سمة بائع",
                ["Admin.ActivityLogType.DeleteVendor"] = "حذف بائع",
                ["Admin.ActivityLogType.DeleteWarehouse"] = "حذف مستودع",
                ["Admin.ActivityLogType.DeleteWidget"] = "حذف عنصر واجهة",
                ["Admin.ActivityLogType.EditActivityLogTypes"] = "تعديل أنواع سجل النشاط",
                ["Admin.ActivityLogType.EditAddressAttributeValue"] = "تعديل قيمة سمة عنوان",
                ["Admin.ActivityLogType.EditAddressAttribute"] = "تعديل سمة عنوان",
                ["Admin.ActivityLogType.EditAffiliate"] = "تعديل مسوق",
                ["Admin.ActivityLogType.EditBlogPost"] = "تعديل تدوينة",
                ["Admin.ActivityLogType.EditCampaign"] = "تعديل حملة",
                ["Admin.ActivityLogType.EditCategory"] = "تعديل قسم",
                ["Admin.ActivityLogType.EditCheckoutAttribute"] = "تعديل سمة دفع",
                ["Admin.ActivityLogType.EditCountry"] = "تعديل دولة",
                ["Admin.ActivityLogType.EditCurrency"] = "تعديل عملة",
                ["Admin.ActivityLogType.EditCustomerAttributeValue"] = "تعديل قيمة سمة عميل",
                ["Admin.ActivityLogType.EditCustomerAttribute"] = "تعديل سمة عميل",
                ["Admin.ActivityLogType.EditCustomerRole"] = "تعديل دور عميل",
                ["Admin.ActivityLogType.EditCustomer"] = "تعديل عميل",
                ["Admin.ActivityLogType.EditDiscount"] = "تعديل خصم",
                ["Admin.ActivityLogType.EditEmailAccount"] = "تعديل حساب بريد إلكتروني",
                ["Admin.ActivityLogType.EditFilterLevelValue"] = "تعديل قيمة مستوى تصفية",
                ["Admin.ActivityLogType.EditLanguage"] = "تعديل لغة",
                ["Admin.ActivityLogType.EditManufacturer"] = "تعديل شركة",
                ["Admin.ActivityLogType.EditMeasureDimension"] = "تعديل وحدة قياس أبعاد",
                ["Admin.ActivityLogType.EditMeasureWeight"] = "تعديل وحدة قياس وزن",
                ["Admin.ActivityLogType.EditMenuItem"] = "تعديل عنصر قائمة",
                ["Admin.ActivityLogType.EditMenu"] = "تعديل قائمة",
                ["Admin.ActivityLogType.EditMessageTemplate"] = "تعديل قالب رسالة",
                ["Admin.ActivityLogType.EditNews"] = "تعديل خبر",
                ["Admin.ActivityLogType.EditOrder"] = "تعديل طلب",
                ["Admin.ActivityLogType.EditPlugin"] = "تعديل إضافة برمجية",
                ["Admin.ActivityLogType.EditProductAttribute"] = "تعديل سمة منتج",
                ["Admin.ActivityLogType.EditProductReview"] = "تعديل مراجعة منتج",
                ["Admin.ActivityLogType.EditProduct"] = "تعديل منتج",
                ["Admin.ActivityLogType.EditPromotionProviders"] = "تعديل مزودي العروض الترويجية",
                ["Admin.ActivityLogType.EditReturnRequest"] = "تعديل طلب إرجاع",
                ["Admin.ActivityLogType.EditReviewType"] = "تعديل نوع مراجعة",
                ["Admin.ActivityLogType.EditSettings"] = "تعديل الإعدادات",
                ["Admin.ActivityLogType.EditSpecAttributeGroup"] = "تعديل مجموعة سمات مواصفات",
                ["Admin.ActivityLogType.EditSpecAttribute"] = "تعديل سمة مواصفات",
                ["Admin.ActivityLogType.EditStateProvince"] = "تعديل ولاية أو محافظة",
                ["Admin.ActivityLogType.EditStore"] = "تعديل متجر",
                ["Admin.ActivityLogType.EditSubscriptionType"] = "تعديل نوع اشتراك",
                ["Admin.ActivityLogType.EditTask"] = "تعديل مهمة",
                ["Admin.ActivityLogType.EditTopic"] = "تعديل موضوع",
                ["Admin.ActivityLogType.EditVendorAttributeValue"] = "تعديل قيمة سمة بائع",
                ["Admin.ActivityLogType.EditVendorAttribute"] = "تعديل سمة بائع",
                ["Admin.ActivityLogType.EditVendor"] = "تعديل بائع",
                ["Admin.ActivityLogType.EditWarehouse"] = "تعديل مستودع",
                ["Admin.ActivityLogType.EditWidget"] = "تعديل عنصر واجهة",
                ["Admin.ActivityLogType.ExportCategories"] = "تصدير الأقسام",
                ["Admin.ActivityLogType.ExportCustomers"] = "تصدير العملاء",
                ["Admin.ActivityLogType.ExportFilterLevelValues"] = "تصدير قيم مستويات التصفية",
                ["Admin.ActivityLogType.ExportManufacturers"] = "تصدير الشركات",
                ["Admin.ActivityLogType.ExportNewsLetterSubscriptions"] = "تصدير اشتراكات النشرة البريدية",
                ["Admin.ActivityLogType.ExportOrders"] = "تصدير الطلبات",
                ["Admin.ActivityLogType.ExportProducts"] = "تصدير المنتجات",
                ["Admin.ActivityLogType.ExportStates"] = "تصدير الولايات والمحافظات",
                ["Admin.ActivityLogType.Impersonation.Finished"] = "جلسة انتحال شخصية عميل - انتهت",
                ["Admin.ActivityLogType.Impersonation.Started"] = "جلسة انتحال شخصية عميل - بدأت",
                ["Admin.ActivityLogType.ImportCategories"] = "استيراد الأقسام",
                ["Admin.ActivityLogType.ImportCustomers"] = "استيراد العملاء",
                ["Admin.ActivityLogType.ImportFilterLevelValues"] = "استيراد قيم مستويات التصفية",
                ["Admin.ActivityLogType.ImportManufacturers"] = "استيراد الشركات",
                ["Admin.ActivityLogType.ImportNewsLetterSubscriptions"] = "استيراد اشتراكات النشرة البريدية",
                ["Admin.ActivityLogType.ImportProducts"] = "استيراد المنتجات",
                ["Admin.ActivityLogType.ImportStates"] = "استيراد الولايات والمحافظات",
                ["Admin.ActivityLogType.InstallNewPlugin"] = "تثبيت إضافة برمجية جديدة",
                ["Admin.ActivityLogType.PublicStore.AddBlogComment"] = "المتجر: إضافة تعليق على تدوينة",
                ["Admin.ActivityLogType.PublicStore.AddForumPost"] = "المتجر: إضافة مشاركة في المنتدى",
                ["Admin.ActivityLogType.PublicStore.AddForumTopic"] = "المتجر: إضافة موضوع في المنتدى",
                ["Admin.ActivityLogType.PublicStore.AddNewsComment"] = "المتجر: إضافة تعليق على خبر",
                ["Admin.ActivityLogType.PublicStore.AddProductReview"] = "المتجر: إضافة مراجعة منتج",
                ["Admin.ActivityLogType.PublicStore.AddToCompareList"] = "المتجر: إضافة إلى قائمة المقارنة",
                ["Admin.ActivityLogType.PublicStore.AddToShoppingCart"] = "المتجر: إضافة إلى سلة التسوق",
                ["Admin.ActivityLogType.PublicStore.ContactUs"] = "المتجر: استخدام نموذج اتصل بنا",
                ["Admin.ActivityLogType.PublicStore.DeleteForumPost"] = "المتجر: حذف مشاركة من المنتدى",
                ["Admin.ActivityLogType.PublicStore.DeleteForumTopic"] = "المتجر: حذف موضوع من المنتدى",
                ["Admin.ActivityLogType.PublicStore.EditForumPost"] = "المتجر: تعديل مشاركة في المنتدى",
                ["Admin.ActivityLogType.PublicStore.EditForumTopic"] = "المتجر: تعديل موضوع في المنتدى",
                ["Admin.ActivityLogType.PublicStore.FailedLogin"] = "المتجر: فشل تسجيل الدخول",
                ["Admin.ActivityLogType.PublicStore.Logout"] = "المتجر: تسجيل الخروج",
                ["Admin.ActivityLogType.PublicStore.PasswordChanged"] = "المتجر: تغيير كلمة المرور",
                ["Admin.ActivityLogType.PublicStore.PlaceOrder"] = "المتجر: تقديم طلب",
                ["Admin.ActivityLogType.PublicStore.SendPM"] = "المتجر: إرسال رسالة خاصة",
                ["Admin.ActivityLogType.PublicStore.SuccessfulLogin"] = "المتجر: تسجيل دخول ناجح",
                ["Admin.ActivityLogType.PublicStore.ViewCategory"] = "المتجر: عرض قسم",
                ["Admin.ActivityLogType.PublicStore.ViewManufacturer"] = "المتجر: عرض شركة",
                ["Admin.ActivityLogType.PublicStore.ViewProduct"] = "المتجر: عرض منتج",
                ["Admin.ActivityLogType.UninstallPlugin"] = "إلغاء تثبيت إضافة برمجية",
                ["Admin.ActivityLogType.UpdatePlugin"] = "تحديث إضافة برمجية",
                ["Admin.ActivityLogType.UploadIcons"] = "رفع أيقونة الموقع وأيقونات التطبيق",
                ["Admin.ActivityLogType.UploadNewPlugin"] = "رفع إضافة برمجية",
                ["Admin.ActivityLogType.UploadNewTheme"] = "رفع قالب تصميم"
            }, arabic.Id);
    }

    public override void Down()
    {
        //add the downgrade logic if necessary 
    }
}