using FluentMigrator;
using Nop.Core.Infrastructure;
using Nop.Data;
using Nop.Data.Migrations;
using Nop.Services.Localization;

namespace Nop.Web.Framework.Migrations.UpgradeTo500;

/// <summary>
/// One-line descriptions of every permission, shown as tooltips on the customer role page
/// </summary>
[NopUpdateMigration("2026-09-29 23:45:00", "5.00", UpdateMigrationType.Localization)]
public class PermissionDescriptionsLocalizationMigration : MigrationBase
{
    /// <summary>Collect the UP migration expressions</summary>
    public override void Up()
    {
        if (!DataSettingsManager.IsDatabaseInstalled())
            return;

        //do not use DI, because it produces exception on the installation process
        var localizationService = EngineContext.Current.Resolve<ILocalizationService>();
        var languageService = EngineContext.Current.Resolve<ILanguageService>();

        localizationService.AddOrUpdateLocaleResource(new Dictionary<string, string>
        {
            ["Admin.Customers.CustomerRoles.Permissions.Description.Security.AccessAdminPanel"] = "Lets them sign in to the admin area. Without it, nothing else on this page has any effect.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Security.ManagePermissions"] = "Open the Access control list page and change what every role may do, including their own.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Orders.OrdersView"] = "See the order list and open orders: items, customer, address and payment status.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Orders.OrdersCreateEditDelete"] = "Change orders: status, items, prices, addresses, notes, and delete orders. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Orders.OrdersImportExport"] = "Export orders to Excel or XML and import them back.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Orders.ShipmentsView"] = "See shipments and their tracking and delivery status.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Orders.ShipmentsCreateEditDelete"] = "Create shipments, mark them shipped or delivered, and delete them. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Orders.ReturnRequestsView"] = "See the return requests customers send.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Orders.ReturnRequestsCreateEditDelete"] = "Accept, reject, edit and delete return requests. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Orders.CurrentCartsManage"] = "See what customers have in their carts and wishlists right now.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductsView"] = "See the product list and open products.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductsCreateEditDelete"] = "Add, edit and delete products: names, prices, stock, pictures. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductsImportExport"] = "Export products to Excel or XML and import them in bulk.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.CategoriesView"] = "See the category list and open categories.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.CategoriesCreateEditDelete"] = "Add, edit and delete categories. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.CategoriesImportExport"] = "Export categories to Excel or XML and import them.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ManufacturerView"] = "See the manufacturer (brand) list.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ManufacturerCreateEditDelete"] = "Add, edit and delete manufacturers. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ManufacturerImportExport"] = "Export manufacturers to Excel or XML and import them.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductAttributesView"] = "See product attributes (options such as size or colour).",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductAttributesCreateEditDelete"] = "Add, edit and delete product attributes. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.SpecificationAttributesView"] = "See specification attributes (the details shown in a product's specs table).",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.SpecificationAttributesCreateEditDelete"] = "Add, edit and delete specification attributes. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.CheckoutAttributesView"] = "See checkout attributes (extra questions asked at checkout, such as gift wrapping).",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.CheckoutAttributesCreateEditDelete"] = "Add, edit and delete checkout attributes. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductReviewsView"] = "See the reviews customers write on products.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductReviewsCreateEditDelete"] = "Approve, edit, reply to and delete product reviews. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductTagsView"] = "See product tags.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductTagsCreateEditDelete"] = "Edit and delete product tags. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.FilterLevelValueView"] = "See filter level values (the make, model and year style filters).",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.FilterLevelValueCreateEditDelete"] = "Add, edit and delete filter level values. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.FilterLevelValueImportExport"] = "Export filter level values to Excel and import them.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.CustomersView"] = "See the customer list and open customer accounts.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.CustomersCreateEditDelete"] = "Add, edit and delete customers, reset passwords and change their roles. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.CustomersImportExport"] = "Export customers to Excel or XML and import them.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.CustomersImpersonation"] = "Sign in to the store as a customer, for example to place an order for them.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.CustomerRolesView"] = "See the list of customer roles.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.CustomerRolesCreateEditDelete"] = "Create, edit and delete roles and give them permissions (only ones they have). Also needs View and \"ACL. Manage\".",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.VendorsView"] = "See the vendor list.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.VendorsCreateEditDelete"] = "Add, edit and delete vendors. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.ActivityLogView"] = "See the activity log: what each customer and admin did, and when.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.ActivityLogDelete"] = "Delete entries from the activity log.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.ActivityLogManageTypes"] = "Choose which kinds of activity get logged.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.GDPRManage"] = "Handle GDPR requests: export or delete a customer's personal data.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.DiscountsView"] = "See discounts and coupon codes.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.DiscountsCreateEditDelete"] = "Add, edit and delete discounts and coupon codes. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.AffiliatesView"] = "See affiliates and the orders they brought in.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.AffiliatesCreateEditDelete"] = "Add, edit and delete affiliates. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.CampaignsView"] = "See email campaigns.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.CampaignsCreateEdit"] = "Create and edit email campaigns. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.CampaignsDelete"] = "Delete email campaigns.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.CampaignsSendEmails"] = "Send a campaign to newsletter subscribers.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.SubscribersView"] = "See newsletter subscribers.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.SubscribersCreateEditDelete"] = "Add, edit and delete newsletter subscribers. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.SubscribersImportExport"] = "Export newsletter subscribers to CSV and import them.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.SubscriptionTypeView"] = "See newsletter lists (subscription types).",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.SubscriptionTypeCreateEditDelete"] = "Add, edit and delete newsletter lists. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.TopicsView"] = "See topics (pages such as About us, Shipping info, Privacy).",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.TopicsCreateEditDelete"] = "Add, edit and delete topic pages. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.MenusView"] = "See the store's menus.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.MenusCreateEditDelete"] = "Add, edit and delete the store's menus and their items. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.MessageTemplatesView"] = "See the email templates the store sends (order placed, shipped, and so on).",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.MessageTemplatesCreateEditDelete"] = "Edit the wording of email templates and turn them on or off. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.NewsView"] = "See news items.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.NewsCreateEditDelete"] = "Add, edit and delete news items. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.NewsCommentsView"] = "See comments on news items.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.NewsCommentsCreateEditDelete"] = "Approve, edit and delete news comments. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.BlogView"] = "See blog posts.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.BlogCreateEditDelete"] = "Write, edit and delete blog posts. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.BlogCommentsView"] = "See comments on blog posts.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.BlogCommentsCreateEditDelete"] = "Approve, edit and delete blog comments. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.PollsView"] = "See polls.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.PollsCreateEditDelete"] = "Add, edit and delete polls. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.ForumsView"] = "See forums.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.ForumsCreateEditDelete"] = "Add, edit and delete forums and forum groups. Also turn on View.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Reports.SalesSummary"] = "See the sales summary report (sales by day, week or month).",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Reports.Bestsellers"] = "See the best-selling products report.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Reports.LowStock"] = "See products that are running out of stock.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Reports.ProductsNeverPurchased"] = "See products nobody has bought yet.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Reports.CountrySales"] = "See sales broken down by country.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Reports.CustomersByOrderTotal"] = "See the customers who spent the most.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Reports.CustomersByNumberOfOrders"] = "See the customers who ordered most often.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Reports.RegisteredCustomers"] = "See how many customers registered over time.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageSettings"] = "Change the store's settings pages (catalog, orders, customers, and so on).",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageAdvancedSettings"] = "Change advanced settings: the raw list of all settings, filter levels, GDPR and payment restrictions.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageStores"] = "Change store details such as name, URL and SSL.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageCountries"] = "Add, edit and delete countries and their states or provinces.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageLanguages"] = "Add and edit languages and their translated texts.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageCurrencies"] = "Add and edit currencies and exchange rates.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManagePaymentMethods"] = "Turn payment methods on or off and configure them.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageShippingSettings"] = "Configure shipping methods, rates and delivery dates.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageTaxSettings"] = "Configure taxes and tax categories.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageEmailAccounts"] = "Configure the email accounts the store sends mail from.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageACL"] = "Choose which roles can see specific products, categories, manufacturers and pages. Also needed to open role pages.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManagePlugins"] = "Install, uninstall and configure plugins.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManagePluginAndWidgetLists"] = "See the lists of plugins and widgets and turn them on or off.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageWidgets"] = "Turn widgets on or off and configure them.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.System.ManageSystemLog"] = "See and clear the system error log.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.System.ManageMessageQueue"] = "See and resend the queue of outgoing emails.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.System.ManageMaintenance"] = "Run maintenance: delete guest accounts, clear caches, back up the database.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.System.ManageScheduleTasks"] = "Run, edit and pause scheduled background tasks.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.System.ManageAppSettings"] = "Change server settings (appsettings.json): database, caching, hosting. Mistakes can take the store down.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.System.HtmlEditor.ManagePictures"] = "Upload and manage pictures inside the text editor.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.PublicStore.PublicStoreAllowNavigation"] = "Browse the storefront. Without it they only see the sign-in page.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.PublicStore.DisplayPrices"] = "See product prices in the store.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.PublicStore.EnableShoppingCart"] = "Add products to the cart and place orders.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.PublicStore.AccessClosedStore"] = "Browse the store while it is closed for maintenance.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationCoreConfiguration"] = "Change the NopStation core plugin's settings.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationCoreLicense"] = "See and change NopStation plugin licenses.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationFeatures"] = "Turn NopStation features on or off.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ShowNopStationDocumentations"] = "See the NopStation help and documentation links.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationSmsConfiguration"] = "Configure SMS sending.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationSmsProviders"] = "Choose and configure the SMS provider.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationSmsQueue"] = "See and resend queued SMS messages.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationSmsTemplates"] = "Edit the wording of SMS messages.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationProductTab"] = "Manage the extra tabs shown on product pages.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageAdminReportExporterConfiguration"] = "Configure the report exporter plugin.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageAdminReportExporter"] = "Export admin reports to files.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationSliders"] = "Create and edit the sliders shown around the store.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationCancelOrder"] = "Configure whether and when customers can cancel their own orders.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageCustomerReminders"] = "Configure reminder emails to customers (abandoned carts, pending orders).",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationMegaMenu"] = "Configure the store's mega menu.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationOCarousels"] = "Create and edit product carousels.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationPictureZoom"] = "Configure picture zoom on product pages.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationPrevNextProduct"] = "Configure the previous/next product buttons.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationProduct360View"] = "Manage 360° product views.",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationProductRibbon"] = "Create and edit product ribbons (labels such as \"New\" or \"Sale\").",
            ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationQuickView"] = "Configure the quick view popup for products."
        });

        var arabic = languageService.GetAllLanguages(showHidden: true)
            .FirstOrDefault(language => language.LanguageCulture.StartsWith("ar", StringComparison.OrdinalIgnoreCase));
        if (arabic is not null)
            localizationService.AddOrUpdateLocaleResource(new Dictionary<string, string>
            {
                ["Admin.Customers.CustomerRoles.Permissions.Description.Security.AccessAdminPanel"] = "يسمح لهم بدخول لوحة الإدارة. بدونها لا تعمل أي صلاحية أخرى في هذه الصفحة.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Security.ManagePermissions"] = "فتح صفحة قائمة الصلاحيات وتغيير صلاحيات كل الأدوار، بما فيها أدوارهم.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Orders.OrdersView"] = "عرض قائمة الطلبات وفتح أي طلب: المنتجات والعميل والعنوان وحالة الدفع.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Orders.OrdersCreateEditDelete"] = "تعديل الطلبات: الحالة والمنتجات والأسعار والعناوين والملاحظات، وحذف الطلبات. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Orders.OrdersImportExport"] = "تصدير الطلبات إلى Excel أو XML واستيرادها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Orders.ShipmentsView"] = "عرض الشحنات وحالة التتبع والتسليم.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Orders.ShipmentsCreateEditDelete"] = "إنشاء الشحنات وتحديدها كمشحونة أو مُسلّمة وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Orders.ReturnRequestsView"] = "عرض طلبات الإرجاع التي يرسلها العملاء.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Orders.ReturnRequestsCreateEditDelete"] = "قبول طلبات الإرجاع ورفضها وتعديلها وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Orders.CurrentCartsManage"] = "عرض ما في سلال العملاء وقوائم أمنياتهم الآن.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductsView"] = "عرض قائمة المنتجات وفتح أي منتج.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductsCreateEditDelete"] = "إضافة المنتجات وتعديلها وحذفها: الأسماء والأسعار والمخزون والصور. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductsImportExport"] = "تصدير المنتجات إلى Excel أو XML واستيرادها دفعة واحدة.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.CategoriesView"] = "عرض قائمة الفئات وفتح أي فئة.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.CategoriesCreateEditDelete"] = "إضافة الفئات وتعديلها وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.CategoriesImportExport"] = "تصدير الفئات إلى Excel أو XML واستيرادها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ManufacturerView"] = "عرض قائمة المصنّعين (العلامات التجارية).",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ManufacturerCreateEditDelete"] = "إضافة المصنّعين وتعديلهم وحذفهم. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ManufacturerImportExport"] = "تصدير المصنّعين إلى Excel أو XML واستيرادهم.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductAttributesView"] = "عرض سمات المنتج (خيارات مثل المقاس أو اللون).",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductAttributesCreateEditDelete"] = "إضافة سمات المنتج وتعديلها وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.SpecificationAttributesView"] = "عرض سمات المواصفات (التفاصيل الظاهرة في جدول مواصفات المنتج).",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.SpecificationAttributesCreateEditDelete"] = "إضافة سمات المواصفات وتعديلها وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.CheckoutAttributesView"] = "عرض سمات الدفع (أسئلة إضافية عند إتمام الطلب مثل تغليف الهدايا).",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.CheckoutAttributesCreateEditDelete"] = "إضافة سمات الدفع وتعديلها وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductReviewsView"] = "عرض التقييمات التي يكتبها العملاء على المنتجات.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductReviewsCreateEditDelete"] = "اعتماد تقييمات المنتجات وتعديلها والرد عليها وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductTagsView"] = "عرض وسوم المنتجات.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.ProductTagsCreateEditDelete"] = "تعديل وسوم المنتجات وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.FilterLevelValueView"] = "عرض قيم مستويات الفلترة (فلاتر مثل الماركة والطراز والسنة).",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.FilterLevelValueCreateEditDelete"] = "إضافة قيم مستويات الفلترة وتعديلها وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Catalog.FilterLevelValueImportExport"] = "تصدير قيم مستويات الفلترة إلى Excel واستيرادها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.CustomersView"] = "عرض قائمة العملاء وفتح حساباتهم.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.CustomersCreateEditDelete"] = "إضافة العملاء وتعديلهم وحذفهم، وإعادة تعيين كلمات المرور وتغيير أدوارهم. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.CustomersImportExport"] = "تصدير العملاء إلى Excel أو XML واستيرادهم.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.CustomersImpersonation"] = "الدخول إلى المتجر باسم أحد العملاء، مثلاً لإنشاء طلب نيابةً عنه.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.CustomerRolesView"] = "عرض قائمة أدوار العملاء.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.CustomerRolesCreateEditDelete"] = "إنشاء الأدوار وتعديلها وحذفها ومنحها صلاحيات (مما يملكونه فقط). يحتاج أيضاً \"عرض\" و\"إدارة ACL\".",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.VendorsView"] = "عرض قائمة البائعين.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.VendorsCreateEditDelete"] = "إضافة البائعين وتعديلهم وحذفهم. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.ActivityLogView"] = "عرض سجل النشاطات: ما فعله كل عميل ومشرف ومتى.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.ActivityLogDelete"] = "حذف سجلات من سجل النشاطات.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.ActivityLogManageTypes"] = "اختيار أنواع النشاطات التي تُسجَّل.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Customers.GDPRManage"] = "معالجة طلبات حماية البيانات: تصدير بيانات العميل الشخصية أو حذفها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.DiscountsView"] = "عرض الخصومات وأكواد القسائم.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.DiscountsCreateEditDelete"] = "إضافة الخصومات وأكواد القسائم وتعديلها وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.AffiliatesView"] = "عرض المسوّقين بالعمولة والطلبات التي جلبوها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.AffiliatesCreateEditDelete"] = "إضافة المسوّقين بالعمولة وتعديلهم وحذفهم. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.CampaignsView"] = "عرض الحملات البريدية.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.CampaignsCreateEdit"] = "إنشاء الحملات البريدية وتعديلها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.CampaignsDelete"] = "حذف الحملات البريدية.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.CampaignsSendEmails"] = "إرسال حملة إلى مشتركي النشرة البريدية.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.SubscribersView"] = "عرض مشتركي النشرة البريدية.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.SubscribersCreateEditDelete"] = "إضافة مشتركي النشرة البريدية وتعديلهم وحذفهم. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.SubscribersImportExport"] = "تصدير مشتركي النشرة البريدية إلى CSV واستيرادهم.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.SubscriptionTypeView"] = "عرض قوائم النشرة البريدية (أنواع الاشتراك).",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Promotions.SubscriptionTypeCreateEditDelete"] = "إضافة قوائم النشرة البريدية وتعديلها وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.TopicsView"] = "عرض الصفحات النصية (مثل من نحن ومعلومات الشحن والخصوصية).",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.TopicsCreateEditDelete"] = "إضافة الصفحات النصية وتعديلها وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.MenusView"] = "عرض قوائم المتجر.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.MenusCreateEditDelete"] = "إضافة قوائم المتجر وعناصرها وتعديلها وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.MessageTemplatesView"] = "عرض قوالب الرسائل التي يرسلها المتجر (تأكيد الطلب، الشحن، وغيرها).",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.MessageTemplatesCreateEditDelete"] = "تعديل نصوص قوالب الرسائل وتفعيلها أو إيقافها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.NewsView"] = "عرض الأخبار.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.NewsCreateEditDelete"] = "إضافة الأخبار وتعديلها وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.NewsCommentsView"] = "عرض التعليقات على الأخبار.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.NewsCommentsCreateEditDelete"] = "اعتماد تعليقات الأخبار وتعديلها وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.BlogView"] = "عرض تدوينات المدونة.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.BlogCreateEditDelete"] = "كتابة تدوينات المدونة وتعديلها وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.BlogCommentsView"] = "عرض التعليقات على التدوينات.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.BlogCommentsCreateEditDelete"] = "اعتماد تعليقات المدونة وتعديلها وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.PollsView"] = "عرض استطلاعات الرأي.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.PollsCreateEditDelete"] = "إضافة استطلاعات الرأي وتعديلها وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.ForumsView"] = "عرض المنتديات.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ContentManagement.ForumsCreateEditDelete"] = "إضافة المنتديات ومجموعاتها وتعديلها وحذفها. فعّل \"عرض\" أيضاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Reports.SalesSummary"] = "عرض تقرير ملخص المبيعات (حسب اليوم أو الأسبوع أو الشهر).",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Reports.Bestsellers"] = "عرض تقرير المنتجات الأكثر مبيعاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Reports.LowStock"] = "عرض المنتجات التي أوشك مخزونها على النفاد.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Reports.ProductsNeverPurchased"] = "عرض المنتجات التي لم يشترها أحد بعد.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Reports.CountrySales"] = "عرض المبيعات موزعة حسب الدولة.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Reports.CustomersByOrderTotal"] = "عرض العملاء الأكثر إنفاقاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Reports.CustomersByNumberOfOrders"] = "عرض العملاء الأكثر طلباً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Reports.RegisteredCustomers"] = "عرض عدد العملاء المسجلين خلال الفترات الزمنية.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageSettings"] = "تغيير صفحات إعدادات المتجر (الكتالوج والطلبات والعملاء وغيرها).",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageAdvancedSettings"] = "تغيير الإعدادات المتقدمة: قائمة كل الإعدادات الخام، ومستويات الفلترة، وحماية البيانات، وقيود الدفع.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageStores"] = "تغيير بيانات المتجر مثل الاسم والرابط وSSL.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageCountries"] = "إضافة الدول ومناطقها وتعديلها وحذفها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageLanguages"] = "إضافة اللغات ونصوصها المترجمة وتعديلها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageCurrencies"] = "إضافة العملات وأسعار الصرف وتعديلها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManagePaymentMethods"] = "تفعيل طرق الدفع أو إيقافها وضبط إعداداتها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageShippingSettings"] = "ضبط طرق الشحن وأسعاره ومواعيد التسليم.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageTaxSettings"] = "ضبط الضرائب وفئاتها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageEmailAccounts"] = "ضبط حسابات البريد التي يرسل منها المتجر الرسائل.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageACL"] = "تحديد الأدوار التي يمكنها رؤية منتجات أو فئات أو مصنّعين أو صفحات معيّنة. مطلوبة أيضاً لفتح صفحات الأدوار.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManagePlugins"] = "تثبيت الإضافات وإلغاء تثبيتها وضبط إعداداتها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManagePluginAndWidgetLists"] = "عرض قوائم الإضافات والودجات وتفعيلها أو إيقافها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.Configuration.ManageWidgets"] = "تفعيل الودجات أو إيقافها وضبط إعداداتها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.System.ManageSystemLog"] = "عرض سجل أخطاء النظام ومسحه.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.System.ManageMessageQueue"] = "عرض قائمة الرسائل الصادرة وإعادة إرسالها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.System.ManageMaintenance"] = "تنفيذ أعمال الصيانة: حذف حسابات الزوار، ومسح الذاكرة المؤقتة، ونسخ قاعدة البيانات احتياطياً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.System.ManageScheduleTasks"] = "تشغيل المهام المجدولة وتعديلها وإيقافها مؤقتاً.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.System.ManageAppSettings"] = "تغيير إعدادات الخادم (appsettings.json): قاعدة البيانات والذاكرة المؤقتة والاستضافة. أي خطأ قد يوقف المتجر.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.System.HtmlEditor.ManagePictures"] = "رفع الصور وإدارتها داخل محرر النصوص.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.PublicStore.PublicStoreAllowNavigation"] = "تصفح واجهة المتجر. بدونها لا يرون إلا صفحة تسجيل الدخول.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.PublicStore.DisplayPrices"] = "رؤية أسعار المنتجات في المتجر.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.PublicStore.EnableShoppingCart"] = "إضافة المنتجات إلى السلة وإتمام الطلبات.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.PublicStore.AccessClosedStore"] = "تصفح المتجر أثناء إغلاقه للصيانة.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationCoreConfiguration"] = "تغيير إعدادات إضافة NopStation الأساسية.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationCoreLicense"] = "عرض تراخيص إضافات NopStation وتغييرها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationFeatures"] = "تفعيل ميزات NopStation أو إيقافها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ShowNopStationDocumentations"] = "عرض روابط المساعدة والتوثيق الخاصة بـ NopStation.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationSmsConfiguration"] = "ضبط إعدادات إرسال الرسائل النصية.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationSmsProviders"] = "اختيار مزوّد الرسائل النصية وضبط إعداداته.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationSmsQueue"] = "عرض الرسائل النصية في قائمة الانتظار وإعادة إرسالها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationSmsTemplates"] = "تعديل نصوص الرسائل النصية.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationProductTab"] = "إدارة التبويبات الإضافية الظاهرة في صفحات المنتجات.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageAdminReportExporterConfiguration"] = "ضبط إعدادات إضافة تصدير التقارير.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageAdminReportExporter"] = "تصدير تقارير الإدارة إلى ملفات.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationSliders"] = "إنشاء العارضات المتحركة في المتجر وتعديلها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationCancelOrder"] = "ضبط إمكانية إلغاء العملاء لطلباتهم ومتى.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageCustomerReminders"] = "ضبط رسائل التذكير للعملاء (السلال المتروكة والطلبات المعلقة).",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationMegaMenu"] = "ضبط القائمة الكبرى في المتجر.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationOCarousels"] = "إنشاء عارضات المنتجات الدوّارة وتعديلها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationPictureZoom"] = "ضبط تكبير الصور في صفحات المنتجات.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationPrevNextProduct"] = "ضبط أزرار المنتج السابق والتالي.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationProduct360View"] = "إدارة عرض المنتجات بزاوية 360°.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationProductRibbon"] = "إنشاء أشرطة المنتجات (علامات مثل \"جديد\" أو \"تخفيض\") وتعديلها.",
                ["Admin.Customers.CustomerRoles.Permissions.Description.ManageNopStationQuickView"] = "ضبط نافذة العرض السريع للمنتجات."
            }, arabic.Id);
    }

    public override void Down()
    {
        //add the downgrade logic if necessary
    }
}